server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/licon
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: root
      maximum-pool-size: 30
  security:
    user:
      name: root
      password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5


mybatis:
  mapper-locations: classpath:mapper:/*.xml